### ISSUE TITLE
XML does generally not work

### ISSUE THREAD

**Issue by OnSive** [fiskaltrust/middleware-demo-dotnet#10]
Is XML supported?

If yes shouldn't the demo be able to run it?

**Comment by TSchmiedlechner** [comment]
Hi @OnSive , thanks for your message and sorry for the late response.
Using XML was already possible previously, but this functionality was not really transparent in the example. 

To make these things easier, we now restructured this repo, and the XML examples you are looking for are can be found here: 
https://github.com/fiskaltrust/middleware-demo-dotnet/tree/master/src/fiskaltrust.Middleware.Demo.Http

Just start the example with the argument `--communication-type Xml`. The requests will still be loaded from the .json files, but XML requests will be sent via HTTP. I hope this helps :)
