### ISSUE TITLE
Woher bekomme ich die CashBox Identification?

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-demo-dotnet#17]
Wenn ich eine **neue Queue** anlege, dann muss ich die **CashBox Identification** festlegen.
Ist das ein willkürlicher Wert oder muss ich einen Speziellen verwenden!?

Ich hätte aus den Anleitungen folgendes verstanden:
Bei der Anlage einer Queue für eine Fiskaly TSE ist bei der CashBox Identification = client ID = OrganizationId aus TSE Config zu verwenden!
**Und wie funktioniert das bei der Diebold TSE!?**

**Comment by MarkusEGruber** [comment]
Die CashBoxIdentification muss eindeutig für die Queue vergeben werden der von Ihnen vergeben wird. Prinzipiell kann dieser willkürlich sein, für Sie muss er Sinn ergeben.
