### ISSUE TITLE
The .exe from the releases needs the ReceiptExamples folder

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-demo-dotnet#6]
the `.exe` downloaded from the releases throws an error because the ReceiptExamples folder is not present.

In the dowloaded `.zip` the folder is present.

**Comment by OnSive** [comment]
Did you extract the ZIP folder or are you running the `.exe` from the ZIP folder?

The right way would be to extract the whole ZIP folder.

**Comment by volllly** [comment]
with the extracted zip it works fine.

but when downloading only the `.exe` from the releases page it does not work.

**Comment by TSchmiedlechner** [comment]
Thanks for the report! We switched our release process to now only serve .zip files containing the RequestExamples folder, so this should be resolved IMO.
